### ISSUE TITLE
no custom slots/events with QUiLoader loaded widgets

### ISSUE THREAD

**Issue by nick133** [mkottman/lqt#15]
Hi, I use QUiLoader like this:

```
local loader = QUiLoader.new()
local uifile = QFile.new( "main.ui" )
uifile:open( { 'ReadOnly' } )
local mainWidget = loader:load( uifile )
w1  = mainWidget:findChild( "MyPushButton" )
```

---

widget is loaded, isWidgetType() returns true, but now both approaches described in examples for signal/slots and events seem not work for w1.

i.e. app crashes after this:
w1:__addmethod( "test()", function() print(1) end )
w1:connect( "2clicked()",  w1, "1test()" )

with error:  bad argument #3 to 'connect' (no such receiver method: 'test()')
( i dont see test() in methods list after __addmethod)

function w1:closeEvent( e ) print(1) end
this one is just silently passing with no result for widget's behaviour. Am I doing something wrong or do those approaches work only with .new() created widgets?

p.s. as a workaround I have to create new empty QWidget and create slots for it - in this case all works fine

**Comment by mkottman** [comment]
This has been discussed [in the Lqt mailing list](http://groups.google.com/group/lqt-bindings/browse_thread/thread/c06be7976494828b) recently, along with explanation why it happens. The workaround you use is the standard way to handle this.

A custom implementation of QUiLoader is also presented in the thread, which creates the objects from Lua. You can check it out if it works for you.

**Comment by nick133** [comment]
thanx for pointing, I'll subscribe for it
