### ISSUE TITLE
Binding templated class by TypeName causes problems.

### ISSUE THREAD

**Issue by vrguru** [mkottman/lqt#2]
Hi. Im trying to use lqt to bind non QT code. I guess this is a general lqt question, but as Mauro is not spending much time on LQT recently I thought I might pop the question here, especially as it also has to do with binding operators, which you have been working on.

Given these (simplified) class declarations:

```
namespace N
{
  template <typename T>
  class Vec3T
  {
  public:

    //typedef T Type;
   // Type _v[3];

    inline Vec3T() {

    }

    /**
    Equality test
    */
    inline bool operator == ( const Vec3T& v ) const {
      return true;
    }

    /** Binary vector subtract. */
    inline const Vec3T operator - ( const Vec3T& rhs ) const {
      return Vec3T( );
    }

    /** Unary vector subtract. */
    inline Vec3T& operator -= ( const Vec3T& rhs ) {

      return *this;
    }

    /** Negation operator. Returns the negative of the Vec3T. */
    inline const Vec3T operator - () const {
      return Vec3T (  );
    }
  };
}    // end of namespace N

namespace N
{

  typedef Vec3T<double> Vec3;

  class Test {
    public:
      Test(N::Vec3 v);
      N::Vec3 doIt();
  };

}    // end of namespace N
```

We can see in the generated XML file that:

```
<FunctionDefinition id="_6" name="operator==" scope="N::Vec3T&lt;T&gt;" context="N::Vec3T&lt;T&gt;" fullname="N::Vec3T&lt;T&gt;::operator==" 
```

It is using the base definition, not the alias. 
The class `N::Vec3T<double>` nor `N::Vec3` is bound to any interface in the generated cpp file.
The class `N::Test` is bound, but all methods containing Vec3 is skipped.

If I change `template <T> class Vec3T` to `class Vec3 {}`, then it works.
So is this part of your ideas of getting templated classes to be exported?

At some point I managed to get the Vec3<double> class to be exported, but ended up with lots of problems, because methods were defined:

```
class C {

 ...
   fooMethod(Vec3 val);

}
```

Was bound as: 

`::fooMethod( Vec3T<double> arg1)` instead of `::fooMethod( N::Vec3 arg1)`

which in some cases caused some problems with namespaces, because it did not add the full namespace for this class.

Also, the negation operator did not work:
It resulted in the following code:

```
static int lqt_bind_11 (lua_State *L) {
  int oldtop = lua_gettop(L);
  N::Vec3T* self = static_cast<N::Vec3T*>(lqtL_toudata(L, 1, "N.Vec3T*"));
  if (NULL==self) {
    lua_pushfstring(L, "Instance of %s has already been deleted in:\n", "N::Vec3T");
    lqtL_pushtrace(L);
    lua_concat(L, 2);
    lua_error(L);
  }
  N::Vec3T const ret = *self -();   <<< Not really valid code. >>>>
  lua_settop(L, oldtop);
  luaL_checkstack(L, 1, "cannot grow stack for return value");
  lqtL_copyudata(L, &ret, "N.Vec3T*");
  return 1;
}
```

Are you actively working on your LQT branch now or is it "put to sleep"??

I think its an excellent piece of software, but it of course need some fixing here and there, as always :-)

**Comment by mkottman** [comment]
Oh well, my 'template support' is currently hand-edited only. Look at [templates.lua](http://github.com/mkottman/lqt/raw/master/generator/templates.lua) at the top (mind the big TODO :).

In order to create a specialized version of the class, you have to specify the templated name, and then the names of classes you want specialized. I have an idea about collecting a list of used template classes from the XML, however I have not started implementing it. It was created with Qt in mind, so it is separated into modules, but after a little modification it may be used without them (just remove the [module_name] references).

The unary- operator is a bug of course, I'll try to fix that. Also, note that the == and != operators are not (yet) bound. 

Right now I'm in the maintenance/bugfix stage of development, so any bugs like these are welcome :)

**Comment by vrguru** [comment]
At least make it possible to add this for each project. Right now this seems to be global, for the whole binding of all QT modules: 

require 'templates'

A first iteration on making it better would be to allow this to be specified at the commandline:

generate_QtGui_cpp: lua -f QtGui_templates.lua -f ...

**Comment by mkottman** [comment]
Done, it is now configurable using the '-c filepath' switch. It defaults to generator/qtemplates.lua, which specifies some useful Qt template classes. For more info, see the [commit message](http://github.com/mkottman/lqt/commit/cc7b5e1a8c07bbc070480a32f43d7878e67a23ab) and [generator/qtemplates.lua](http://github.com/mkottman/lqt/raw/cc7b5e1a8c07bbc070480a32f43d7878e67a23ab/generator/generator.lua).

If you have any trouble using it, please reply.

**Comment by vrguru** [comment]
Well yes, given the above class specifications (N::Vec3T and N::Test) + the following mytemplate.lua:

return {
    -- example usage:
    --
    -- ["ex<T>"] = { "ex<double>", "ex<string>" }
    -- module = { ["ex2<K,V>"] = { "example<char*, int>" } }

```
N = {
    ["Vec3T<T>"] = { "Vec3T<float>", "Vec3T<double>" }  }
```

}

I did not manage to get the class Vec3T<double> bound. Could you try and give me a working example of this? I was not sure if the Template should include N:: or not.. tried both, did not get any classes out of this. Only the constructor for the Test class was exported to cpp code.
